=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::IncidentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IncidentsApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::IncidentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IncidentsApi' do
    it 'should create an instance of IncidentsApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::IncidentsApi)
    end
  end

  # unit tests for api_public_v1_incidents_ack_patch
  # Acknowledge an incident or list of incidents
  # The incident(s) must be currently open.  The user supplied must be a valid VictorOps user and a member of your organization.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body Ack/Resolve payload
  # @param [Hash] opts the optional parameters
  # @return [AckOrResolveResponse]
  describe 'api_public_v1_incidents_ack_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_by_user_ack_patch
  # Acknowledge all incidents for which a user was paged.
  # The incident(s) must be currently open.  The user supplied must be a valid VictorOps user and a member of your organization.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body Ack/Resolve payload
  # @param [Hash] opts the optional parameters
  # @return [AckOrResolveResponse]
  describe 'api_public_v1_incidents_by_user_ack_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_by_user_resolve_patch
  # Resolve all incidents for which a user was paged.
  # The incident(s) must be currently open.  The user supplied must be a valid VictorOps user and a member of your organization.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body Ack/Resolve payload
  # @param [Hash] opts the optional parameters
  # @return [AckOrResolveResponse]
  describe 'api_public_v1_incidents_by_user_resolve_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_get
  # Get current incident information
  # Get a list of the currently open, acknowledged and recently resolved incidents.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [IncidentList]
  describe 'api_public_v1_incidents_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_incident_number_get
  # Get a single incident
  # Get detailed data for a single incident with the provided incident number, if it exists. The incident will be returned regardless if it is active or not.   This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param incident_number The Victorops incident number
  # @param [Hash] opts the optional parameters
  # @return [IncidentInfo]
  describe 'api_public_v1_incidents_incident_number_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_incident_number_notes_get
  # Get the notes associated with an incident
  # Get notes any associated with a single incident with the provided incident number.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param incident_number The incident number
  # @param [Hash] opts the optional parameters
  # @return [Notes]
  describe 'api_public_v1_incidents_incident_number_notes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_incident_number_notes_note_name_delete
  # Delete a Note
  # Delete a note.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param incident_number The incident number
  # @param note_name The html encoded name field of the note
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_public_v1_incidents_incident_number_notes_note_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_incident_number_notes_note_name_put
  # Update a Note
  # Update a note.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param incident_number The incident number
  # @param note_name The html encoded name field of the note
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_public_v1_incidents_incident_number_notes_note_name_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_incident_number_notes_post
  # Create a new Note
  # Create a new note.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param incident_number The incident number
  # @param [Hash] opts the optional parameters
  # @return [Notes]
  describe 'api_public_v1_incidents_incident_number_notes_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_post
  # Create a new incident
  # Create a new incident.  This call replicates the function of our &lt;a href&#x3D;\&quot;https://help.victorops.com/knowledge-base/manual-incident-creation/\&quot;&gt;manual incident creation process&lt;/a&gt;. Monitoring tools and custom integrations should be configured using our &lt;a href&#x3D;\&quot;https://help.victorops.com/knowledge-base/victorops-restendpoint-integration/\&quot;&gt;REST Endpoint&lt;/a&gt;.  The \&quot;isMultiResponder\&quot; option will require a response from each paged user and escalation policy before paging is stopped. The option is available only to Enterprise accounts.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body The incident details
  # @param [Hash] opts the optional parameters
  # @return [Note]
  describe 'api_public_v1_incidents_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_reroute_post
  # Reroute one or more incidents to one or more new routable destinations.
  # Reroute one or more incidents to one or more users and/or escalation policies.  The \&quot;addTargets\&quot; option converts the incident to requiring a response from each paged user and escalation policy before paging is stopped. The option is available only to Enterprise accounts.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body The reroute rules
  # @param [Hash] opts the optional parameters
  # @return [RerouteStatusResponse]
  describe 'api_public_v1_incidents_reroute_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_incidents_resolve_patch
  # Resolve an incident or list of incidents
  # The incident(s) must be currently open.  The user supplied must be a valid VictorOps user and a member of your organization.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body Ack/Resolve payload
  # @param [Hash] opts the optional parameters
  # @return [AckOrResolveResponse]
  describe 'api_public_v1_incidents_resolve_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
