=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::PersonalPagingPolicyValuesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PersonalPagingPolicyValuesApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::PersonalPagingPolicyValuesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PersonalPagingPolicyValuesApi' do
    it 'should create an instance of PersonalPagingPolicyValuesApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::PersonalPagingPolicyValuesApi)
    end
  end

  # unit tests for api_public_v1_policies_types_contacts_get
  # Get the available contact types
  # Get the available contact types  description: \&quot;Email Address\&quot;, type: \&quot;email\&quot; description: \&quot;Phone Number\&quot;, type: \&quot;phone\&quot;  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_policies_types_contacts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_policies_types_notifications_get
  # Get the available notification types
  # Get the available notification types  description: \&quot;Send a push notification to all my devices\&quot;, type: \&quot;push\&quot; description: \&quot;Send an email to an email address\&quot;, type: \&quot;email\&quot; description: \&quot;Send an SMS to a phone number\&quot;, type: \&quot;sms\&quot; description: \&quot;Make a phone call to a phone number\&quot;, type: \&quot;phone\&quot;  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_policies_types_notifications_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_policies_types_timeouts_get
  # Get the available timeout values
  # Get the available timeout values  description: \&quot;If still unacked after 1 minute\&quot;, type: 1 description: \&quot;If still unacked after 5 minutes\&quot;, type: 5 description: \&quot;If still unacked after 10 minutes\&quot;, type: 10 description: \&quot;If still unacked after 15 minutes\&quot;, type: 15 description: \&quot;If still unacked after 20 minutes\&quot;, type: 20 description: \&quot;If still unacked after 25 minutes\&quot;, type: 25 description: \&quot;If still unacked after 30 minutes\&quot;, type: 30 description: \&quot;If still unacked after 45 minutes\&quot;, type: 45 description: \&quot;If still unacked after 60 minutes\&quot;, type: 60  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_policies_types_timeouts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
