=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::PersonalPagingPoliciesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PersonalPagingPoliciesApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::PersonalPagingPoliciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PersonalPagingPoliciesApi' do
    it 'should create an instance of PersonalPagingPoliciesApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::PersonalPagingPoliciesApi)
    end
  end

  # unit tests for api_public_v1_profile_username_policies_get
  # Get the user&#39;s paging policy
  # Get all the paging policy steps for the user on the org associated with the API key  This API may be called a maximum of 1 time per second. 
  # @param username Your username
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_post
  # Create a paging policy step
  # Create a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_get
  # Get a paging policy step
  # Get a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_post
  # Create a rule for a paging policy step
  # Create a rule for a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_put
  # Update a paging policy step
  # Update a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_rule_delete
  # Delete a rule from a paging policy step
  # Delete a rule from a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param rule Rule for a paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_rule_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_rule_get
  # Get a rule from a paging policy step
  # Get a rule from a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param rule Rule for a paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_rule_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_profile_username_policies_step_rule_put
  # Update a rule for a paging policy step
  # Update a rule for a paging policy step  This API may be called a maximum of 2 times per second. 
  # @param username Your username
  # @param step Paging policy step
  # @param rule Rule for a paging policy step
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_profile_username_policies_step_rule_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
