=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::ReportingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReportingApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::ReportingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportingApi' do
    it 'should create an instance of ReportingApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::ReportingApi)
    end
  end

  # unit tests for api_reporting_v1_team_team_oncall_log_get
  # A list of shift changes for a team
  # Returns a log of user shift changes for the specified team. This is historical data, and may be up to 15 minutes behind real-time log data.  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param team The VictorOps team &#39;slug&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :start Return shift changes occurring after this timestamp. The default is the start of the day at midnight. Specify the timestamp in ISO8601 format
  # @option opts [DateTime] :_end Return shift changes occurring before this timestamp. The default is the end of the day at 11:59:59. Specify the timestamp in ISO8601 format
  # @option opts [String] :user_name The VictorOps user ID. Return shift changes occurring during the interval specified for this user. Without this parameter, all relevant users (with respect to the specified interval) are returned
  # @return [OnCallLog]
  describe 'api_reporting_v1_team_team_oncall_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_reporting_v2_incidents_get
  # Get/search incident history
  # Retrieve incident history for your company, searching over date ranges and with filtering options.  This API may be called a maximum of once a minute.  Incident requests are paginated with a offset and limit query string parameters.   The query for incidents is run and offset records are skipped, after which limit records will be returned.  The default offset is 0 and the default limit is 20. The maximum value allowed for limit is 100.  Unless specified otherwise with the parameter currentPhase, the response will only contain resolved incidents.  On return, the total number of records available for that query will be returned in the payload as &#39;total&#39;. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :offset The offset within the set of matching incidents
  # @option opts [Float] :limit The maximum number of matching incidents to return (100 max)
  # @option opts [String] :entity_id The entity ID involved  This is the unique identifier for the entity causing the incident.
  # @option opts [String] :incident_number The incident number as shown in VictorOps Multiple values and ranges are allowed: 4,5,20:50 
  # @option opts [String] :started_after Return incidents started after this timestamp Specify the timestamp in ISO8601 format
  # @option opts [String] :started_before Find incidents started before this timestamp  Specify the timestamp in ISO8601 format
  # @option opts [String] :host The host involved in the incident Multiple values can be separated with commas.
  # @option opts [String] :service The service involved in the incident (if any) Multiple values can be separated with commas.
  # @option opts [String] :current_phase The current phase of the incident \&quot;resolved\&quot;, \&quot;triggered\&quot; or \&quot;acknowledged\&quot;. Multiple values can be separated with commas. By default, response contains only \&quot;resolved\&quot; incidents
  # @option opts [String] :routing_key The original routing of the incident
  # @return [ReportingIncidentList]
  describe 'api_reporting_v2_incidents_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
