=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::RotationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RotationsApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::RotationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RotationsApi' do
    it 'should create an instance of RotationsApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::RotationsApi)
    end
  end

  # unit tests for api_public_v1_teams_team_rotations_get
  # Get all rotation groups for a team
  # Retrieves a list of all rotation groups that exist under the specified team.  This is the current method for retrieving uniquely identifying slugs of existing rotation groups.  This API may be called a maximum of 2 times per second.
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param team The uniquely identifying team slug for which to retrieve rotation groups
  # @param [Hash] opts the optional parameters
  # @return [RotationGroupList]
  describe 'api_public_v1_teams_team_rotations_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
