=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::RoutingKeysApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RoutingKeysApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::RoutingKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RoutingKeysApi' do
    it 'should create an instance of RoutingKeysApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::RoutingKeysApi)
    end
  end

  # unit tests for api_public_v1_org_routing_keys_get
  # List routing keys with associated teams
  # Retrieves a list of routing keys and associated teams. This API may be called a maximum of 2 times per second.
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [ListRoutingKeysResponse]
  describe 'api_public_v1_org_routing_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_org_routing_keys_post
  # Create a new routing key
  # Creates a new routing key with escalation policy mapping. The targets array is a list of escalation policy policySlugs that the new routing key will target. This API may be called a maximum of 2 times per second.
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreateRoutingKeyResponse]
  describe 'api_public_v1_org_routing_keys_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
