=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::ScheduledOverridesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScheduledOverridesApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::ScheduledOverridesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScheduledOverridesApi' do
    it 'should create an instance of ScheduledOverridesApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::ScheduledOverridesApi)
    end
  end

  # unit tests for api_public_v1_overrides_get
  # List the scheduled overrides
  # List all the scheduled overrides on the organization  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_overrides_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_post
  # Creates a new scheduled override
  # Creates a new scheduled override. Start and end dates are in ISO8601 format. E.g. &#x60;2018-09-28&#39;T&#39;05:00:00Z&#x60;  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_overrides_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_assignments_get
  # Get the specified scheduled override
  # Get the specified scheduled override assignments  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param [Hash] opts the optional parameters
  # @return [Array<Assignment>]
  describe 'api_public_v1_overrides_public_id_assignments_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_assignments_policy_slug_delete
  # Delete the scheduled override assignment
  # Delete the scheduled override assignment  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param policy_slug The policySlug of the assignment
  # @param [Hash] opts the optional parameters
  # @return [Assignment]
  describe 'api_public_v1_overrides_public_id_assignments_policy_slug_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_assignments_policy_slug_get
  # Get the specified scheduled override assignment
  # Get the specified scheduled override assignments  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param policy_slug The policySlug of the assignment
  # @param [Hash] opts the optional parameters
  # @return [Assignment]
  describe 'api_public_v1_overrides_public_id_assignments_policy_slug_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_assignments_policy_slug_put
  # Update the scheduled override assignment
  # Update the scheduled override assignment  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param policy_slug The policySlug of the assignment
  # @param body The policy and username we are assigning
  # @param [Hash] opts the optional parameters
  # @return [Assignment]
  describe 'api_public_v1_overrides_public_id_assignments_policy_slug_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_delete
  # Deletes a scheduled override
  # Deletes a scheduled override  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_public_v1_overrides_public_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_overrides_public_id_get
  # Get the specified scheduled override
  # Get the specified scheduled override  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param public_id The publicId of the scheduled override
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_overrides_public_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
