=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for VictorOpsClient::UserContactMethodsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserContactMethodsApi' do
  before do
    # run before each test
    @instance = VictorOpsClient::UserContactMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserContactMethodsApi' do
    it 'should create an instance of UserContactMethodsApi' do
      expect(@instance).to be_instance_of(VictorOpsClient::UserContactMethodsApi)
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_devices_contact_id_delete
  # Delete a contact device for a user
  # Delete a contact device for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [ContactDevice]
  describe 'api_public_v1_user_user_contact_methods_devices_contact_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_devices_contact_id_get
  # Get the indicated contact device for a user
  # Get the indicated contact device for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<ContactDevice>]
  describe 'api_public_v1_user_user_contact_methods_devices_contact_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_devices_contact_id_put
  # Update a contact device for a user
  # Update a contact device for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param body The contact device
  # @param [Hash] opts the optional parameters
  # @return [ContactDevice]
  describe 'api_public_v1_user_user_contact_methods_devices_contact_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_devices_get
  # Get a list of all contact devices for a user
  # Get the contact methods for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ContactDevice>]
  describe 'api_public_v1_user_user_contact_methods_devices_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_emails_contact_id_delete
  # Delete a contact email for a user
  # Delete the indicated contact email for the user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [UserContact]
  describe 'api_public_v1_user_user_contact_methods_emails_contact_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_emails_contact_id_get
  # Get the indicated contact email for a user
  # Get the indicated contact email for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<UserContact>]
  describe 'api_public_v1_user_user_contact_methods_emails_contact_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_emails_get
  # Get a list of all contact emails for a user
  # Get the contact emails for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param [Hash] opts the optional parameters
  # @return [Array<UserContact>]
  describe 'api_public_v1_user_user_contact_methods_emails_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_emails_post
  # Create a contact emails for a user
  # Create a contact email for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param body The contact email
  # @param [Hash] opts the optional parameters
  # @return [UserContact]
  describe 'api_public_v1_user_user_contact_methods_emails_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_get
  # Get a list of all contact methods for a user
  # Get the contact methods for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_public_v1_user_user_contact_methods_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_phones_contact_id_delete
  # Delete a contact phone for a user
  # Delete the indicated contact phone for the user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [UserContact]
  describe 'api_public_v1_user_user_contact_methods_phones_contact_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_phones_contact_id_get
  # Get the indicated contact phone for a user
  # Get the indicated contact phone for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param contact_id The unique contact identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<UserContact>]
  describe 'api_public_v1_user_user_contact_methods_phones_contact_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_phones_get
  # Get a list of all contact phones for a user
  # Get the contact phones for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param [Hash] opts the optional parameters
  # @return [Array<UserContact>]
  describe 'api_public_v1_user_user_contact_methods_phones_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_public_v1_user_user_contact_methods_phones_post
  # Create a contact phones for a user
  # Create a contact phone for a user  This API may be called a maximum of 2 times per second. 
  # @param x_vo_api_id Your API ID
  # @param x_vo_api_key Your API Key
  # @param user The VictorOps user ID
  # @param body The contact phone
  # @param [Hash] opts the optional parameters
  # @return [UserContact]
  describe 'api_public_v1_user_user_contact_methods_phones_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
