=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VictorOpsClient::DeleteUserPayload
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeleteUserPayload' do
  before do
    # run before each test
    @instance = VictorOpsClient::DeleteUserPayload.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeleteUserPayload' do
    it 'should create an instance of DeleteUserPayload' do
      expect(@instance).to be_instance_of(VictorOpsClient::DeleteUserPayload)
    end
  end
  describe 'test attribute "replacement"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "replacement_strategy"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["specifiedUser", "globalAdmin", "teamAdmin", "findReplacement"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.replacement_strategy = value }.not_to raise_error
      # end
    end
  end

end
