=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

# Common files
require 'victor_ops_client/api_client'
require 'victor_ops_client/api_error'
require 'victor_ops_client/version'
require 'victor_ops_client/configuration'

# Models
require 'victor_ops_client/models/ack_or_resolve_by_user_request'
require 'victor_ops_client/models/ack_or_resolve_request'
require 'victor_ops_client/models/ack_or_resolve_response'
require 'victor_ops_client/models/ack_or_resolve_result'
require 'victor_ops_client/models/ack_user'
require 'victor_ops_client/models/active_maintenance_mode'
require 'victor_ops_client/models/add_group_payload'
require 'victor_ops_client/models/add_step_payload'
require 'victor_ops_client/models/add_team_member_payload'
require 'victor_ops_client/models/add_team_payload'
require 'victor_ops_client/models/add_team_response'
require 'victor_ops_client/models/add_user_payload'
require 'victor_ops_client/models/add_user_response'
require 'victor_ops_client/models/assignment'
require 'victor_ops_client/models/batch_add_user_entry'
require 'victor_ops_client/models/batch_user_error'
require 'victor_ops_client/models/contact'
require 'victor_ops_client/models/contact_description'
require 'victor_ops_client/models/contact_device'
require 'victor_ops_client/models/contact_device_add'
require 'victor_ops_client/models/contact_email_add'
require 'victor_ops_client/models/contact_object'
require 'victor_ops_client/models/contact_phone_add'
require 'victor_ops_client/models/contact_type'
require 'victor_ops_client/models/create_escalation_policy'
require 'victor_ops_client/models/create_escalation_policy_entry'
require 'victor_ops_client/models/create_escalation_policy_group'
require 'victor_ops_client/models/create_incident_request'
require 'victor_ops_client/models/create_routing_key_response'
require 'victor_ops_client/models/created_incident'
require 'victor_ops_client/models/delete_user_payload'
require 'victor_ops_client/models/escalation_policy'
require 'victor_ops_client/models/escalation_policy_entry'
require 'victor_ops_client/models/escalation_policy_group'
require 'victor_ops_client/models/escalation_policy_info'
require 'victor_ops_client/models/escalation_policy_info_list'
require 'victor_ops_client/models/escalation_policy_summary'
require 'victor_ops_client/models/get_alert_response'
require 'victor_ops_client/models/incident_info'
require 'victor_ops_client/models/incident_list'
require 'victor_ops_client/models/incident_target'
require 'victor_ops_client/models/incident_transition'
require 'victor_ops_client/models/list_routing_keys_response'
require 'victor_ops_client/models/list_team_members_response'
require 'victor_ops_client/models/list_team_response'
require 'victor_ops_client/models/list_user_response'
require 'victor_ops_client/models/maintenance_mode_state'
require 'victor_ops_client/models/maintenance_mode_target'
require 'victor_ops_client/models/notes'
require 'victor_ops_client/models/notes_payload'
require 'victor_ops_client/models/notification_description'
require 'victor_ops_client/models/notification_object'
require 'victor_ops_client/models/notification_type'
require 'victor_ops_client/models/on_call_and_overrides'
require 'victor_ops_client/models/on_call_entry'
require 'victor_ops_client/models/on_call_escalation_policy_resource'
require 'victor_ops_client/models/on_call_interval'
require 'victor_ops_client/models/on_call_log'
require 'victor_ops_client/models/on_call_now_resource'
require 'victor_ops_client/models/on_call_override'
require 'victor_ops_client/models/on_call_roll'
require 'victor_ops_client/models/on_call_team_resource'
require 'victor_ops_client/models/on_call_teams_resource'
require 'victor_ops_client/models/on_call_type'
require 'victor_ops_client/models/on_call_users_resource'
require 'victor_ops_client/models/paging_policy'
require 'victor_ops_client/models/paging_policy_step'
require 'victor_ops_client/models/paging_policy_step_rule'
require 'victor_ops_client/models/paging_policy_step_rule_add'
require 'victor_ops_client/models/policies'
require 'victor_ops_client/models/policy_schedule'
require 'victor_ops_client/models/remove_team_member_payload'
require 'victor_ops_client/models/reporting_incident_info'
require 'victor_ops_client/models/reporting_incident_list'
require 'victor_ops_client/models/reroute'
require 'victor_ops_client/models/reroute_collection'
require 'victor_ops_client/models/reroute_status'
require 'victor_ops_client/models/reroute_status_response'
require 'victor_ops_client/models/reroute_target_status'
require 'victor_ops_client/models/rotation_group'
require 'victor_ops_client/models/rotation_group_list'
require 'victor_ops_client/models/routing_key_info'
require 'victor_ops_client/models/routing_key_payload'
require 'victor_ops_client/models/routing_key_target'
require 'victor_ops_client/models/scheduled_override'
require 'victor_ops_client/models/scheduled_override_payload'
require 'victor_ops_client/models/scheduled_override_payload_update'
require 'victor_ops_client/models/scheduled_user'
require 'victor_ops_client/models/simple_team_detail'
require 'victor_ops_client/models/subscription_input'
require 'victor_ops_client/models/take_request'
require 'victor_ops_client/models/take_result'
require 'victor_ops_client/models/team'
require 'victor_ops_client/models/team_admin'
require 'victor_ops_client/models/team_admins_response'
require 'victor_ops_client/models/team_detail'
require 'victor_ops_client/models/team_member'
require 'victor_ops_client/models/team_schedule'
require 'victor_ops_client/models/team_schedule_overlay_resource'
require 'victor_ops_client/models/team_schedule_resource'
require 'victor_ops_client/models/team_schedule_roll_resource'
require 'victor_ops_client/models/timeout_description'
require 'victor_ops_client/models/timeout_object'
require 'victor_ops_client/models/timeout_type'
require 'victor_ops_client/models/update_assignment'
require 'victor_ops_client/models/user'
require 'victor_ops_client/models/user_contact'
require 'victor_ops_client/models/user_log'
require 'victor_ops_client/models/user_paging_policy'
require 'victor_ops_client/models/user_schedule'
require 'victor_ops_client/models/user_teams_response'
require 'victor_ops_client/models/v1_user'
require 'victor_ops_client/models/webhook'
require 'victor_ops_client/models/webhook_list'
require 'victor_ops_client/models/webhook_subscription_response'

# APIs
require 'victor_ops_client/api/alerts_api'
require 'victor_ops_client/api/chat_api'
require 'victor_ops_client/api/escalation_policies_api'
require 'victor_ops_client/api/incidents_api'
require 'victor_ops_client/api/maintenance_mode_api'
require 'victor_ops_client/api/notes_api'
require 'victor_ops_client/api/on_call_api'
require 'victor_ops_client/api/personal_paging_policies_api'
require 'victor_ops_client/api/personal_paging_policy_values_api'
require 'victor_ops_client/api/reporting_api'
require 'victor_ops_client/api/rotations_api'
require 'victor_ops_client/api/routing_keys_api'
require 'victor_ops_client/api/scheduled_overrides_api'
require 'victor_ops_client/api/teams_api'
require 'victor_ops_client/api/user_contact_methods_api'
require 'victor_ops_client/api/user_paging_policies_api'
require 'victor_ops_client/api/users_api'
require 'victor_ops_client/api/webhooks_api'

module VictorOpsClient
  class << self
    # Customize default settings for the SDK using block.
    #   VictorOpsClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
