=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'date'

module VictorOpsClient
  class TimeoutType
    
    ONE = 1.freeze
    FIVE = 5.freeze
    TEN = 10.freeze
    FIFTEEN = 15.freeze
    TWENTY = 20.freeze
    TWENTYFIVE = 25.freeze
    THIRTY = 30.freeze
    FOURTHYFIVE = 45.freeze
    SIXTY = 60.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TimeoutType.constants.select { |c| TimeoutType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TimeoutType" if constantValues.empty?
      value
    end
  end
end
