=begin
#VictorOps API

#This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  https protocol is required to use this API.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

OpenAPI spec version: 0.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'date'

module VictorOpsClient
  class TimeoutDescription
    
    N1_MINUTE = 'If still unacked after 1 minute'.freeze
    N5_MINUTE = 'If still unacked after 5 minute'.freeze
    N10_MINUTE = 'If still unacked after 10 minute'.freeze
    N15_MINUTE = 'If still unacked after 15 minute'.freeze
    N20_MINUTE = 'If still unacked after 20 minute'.freeze
    N25_MINUTE = 'If still unacked after 25 minute'.freeze
    N30_MINUTE = 'If still unacked after 30 minute'.freeze
    N45_MINUTE = 'If still unacked after 45 minute'.freeze
    N60_MINUTE = 'If still unacked after 60 minute'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TimeoutDescription.constants.select { |c| TimeoutDescription::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TimeoutDescription" if constantValues.empty?
      value
    end
  end
end
